import { readFile, writeFile } from 'node:fs/promises';

const catalog = JSON.parse(await readFile(new URL('../locales/he.json', import.meta.url), 'utf8'));
for (const [source, translation] of Object.entries(catalog)) {
  if (!source || !translation || !/[\u0590-\u05ff]/u.test(translation) && source !== translation) throw Error(`Missing Hebrew translation: ${source}`);
  const slots = text => [...text.matchAll(/\{\d+\}/g)].map(m => m[0]).sort().join(',');
  if (slots(source) !== slots(translation)) throw Error(`Translation placeholders differ: ${source}`);
}
const quote = text => JSON.stringify(text).replaceAll('$', '\\$');
const files = new Map([
  ['public/app/i18n-catalog.js', '// Generated by scripts/localization.mjs from locales/he.json.\nexport default ' + JSON.stringify(catalog, null, 2) + ';\n'],
  ['android/app/src/main/java/com/fala/app/UiCatalog.kt', '// Generated by scripts/localization.mjs from locales/he.json.\npackage com.fala.app\n\ninternal val hebrewUi = mapOf(\n' + Object.entries(catalog).map(([a,b]) => `    ${quote(a)} to ${quote(b)}`).join(',\n') + '\n)\n'],
]);
for (const [path, value] of files) {
  const url = new URL('../' + path, import.meta.url);
  if (process.argv.includes('--check')) {
    if (await readFile(url, 'utf8').catch(() => '') !== value) throw Error(`Run node scripts/localization.mjs to update ${path}`);
  } else await writeFile(url, value);
}
